---
- name: Download Vector binary
  become: yes
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
- name: Install clickhouse packages
  become: yes
  ansible.builtin.yum:
    name:
      - vector-{{ vector_version }}-1.x86_64.rpm
    disable_gpg_check: true 
- name: Ensure Vector configuration directory exists
  become: yes
  file:
    path: /etc/vector
    state: directory
    mode: '0755'
- name: Deploy Vector configuration
  become: yes
  template:
    src: vector.toml.j2
    dest: /etc/vector/vector.toml
    mode: '0644'
  notify: Restart Vector
